---

- name: Set scoped key from backend variable
  set_fact:
    HEXAA_FRONTEND_SCOPED_KEY: "{{ HEXAA_BACKEND_MASTERKEY.defaultMasterKey }}"
  when:
    - HEXAA_FRONTEND_SCOPED_KEY == ""
    - HEXAA_BACKEND_MASTERKEY is defined
    - HEXAA_BACKEND_MASTERKEY.defaultMasterKey is defined

- fail:
    msg: "The HEXAA backend master key is missing"
  when: HEXAA_FRONTEND_SCOPED_KEY == ""

- fail:
    msg: "The HEXAA backend secret is missing"
  when: HEXAA_BACKEND_SECRET == ""


- name: set network list for the main HTTP server container
  set_fact:
    docker_networks: [{name: "{{ docker_network_name_frontend }}"}]
  tags: [web]
- set_fact:
    docker_networks: "{{ [{'name':  docker_network_name_backend}] + docker_networks }}"
  when: docker_network_name_backend is defined
  tags: [web]


- name: create config directory
  file:
    path: /opt/hexaa/config/frontend
    state: directory
    mode: 0775
    owner: www-data
    group: hbit
  become: true
  register: frontend_config_dir
  tags: web
- name: create ansible generated
  file:
    path: "{{ frontend_config_dir.path }}/00_GENERATED_BY_ANSIBLE"
    state: touch
    mode: 0664
  tags: web
- name: create parameters.yml from template
  template:
    src: parameters.yml.j2
    dest: "{{ frontend_config_dir.path }}/parameters.yml"
  tags: web

- name: create log dir
  file:
    path: /opt/hexaa/logs/frontend
    state: directory
    mode: 0755
    owner: www-data
  register: log_dir
  become: true

- name: copy Shibboleth and Apache config
  copy:
    src: files/
    dest: "{{ frontend_config_dir.path }}"
    owner: www-data
    group: hbit
  become: true
  tags: [web]

- name: create shibboleth config dir
  file:
    path: "{{ frontend_config_dir.path }}/shibboleth/"
    owner: www-data
    group: hbit
    state: directory
    mode: 0775
  become: true
  tags: [web]

- name: copy certs from parent role
  copy:
    src: files/certs
    dest: "{{ frontend_config_dir.path }}/shibboleth/"
    owner: www-data
    group: hbit
  become: true
  tags: [web]

- name: create shibboleth2.xml from template
  template:
    src: shibboleth2.xml.j2
    dest: "{{ frontend_config_dir.path }}/shibboleth/shibboleth2.xml"
  tags: [web]

- name: use the redirect config on port 80
  shell: "mv -f {{ frontend_config_dir.path }}/default-hexaa-ssl-redirect.conf {{ frontend_config_dir.path }}/default-hexaa.conf"
  when: HEXAA_FRONTEND_URL_PROTO == "https"
  tags: [web]
