---

- name: Set scoped key from backend variable
  set_fact:
    HEXAA_FRONTEND_SCOPED_KEY: "{{ HEXAA_BACKEND_MASTERKEY.defaultMasterKey }}"
  when:
    - HEXAA_FRONTEND_SCOPED_KEY == ""
    - HEXAA_BACKEND_MASTERKEY is defined
    - HEXAA_BACKEND_MASTERKEY.defaultMasterKey is defined

- fail:
    msg: "The HEXAA backend master key is missing"
  when: HEXAA_FRONTEND_SCOPED_KEY == ""

- fail:
    msg: "The HEXAA backend secret is missing"
  when: HEXAA_BACKEND_SECRET == ""


- name: set network list for the main HTTP server container
  set_fact:
    docker_networks: [{name: "{{ docker_network_name_frontend }}"}]
- set_fact:
    docker_networks: "{{ [{'name':  docker_network_name_backend}] + docker_networks }}"
  when: docker_network_name_backend is defined


- name: create config directory
  tempfile:
    state: directory
  register: frontend_config_dir
- name: create parameters.yml from template
  template:
    src: parameters.yml.j2
    dest: "{{ frontend_config_dir.path }}/parameters.yml"
- name: set config dir permissions
  file:
    path: "{{ frontend_config_dir.path }}"
    mode: 0755

- name: copy Shibboleth config
  copy:
    src: files/shibboleth
    dest: "{{ frontend_config_dir.path }}"
- name: copy apache config
  copy:
    src: files/default-hexaa.conf
    dest: "{{ frontend_config_dir.path }}/default-hexaa.conf"
