---

- name: ensure shibboleth cert exists
  stat:
    path: "{{ SHIBBOLETH_CERTIFICATE_PATH }}/sp-cert.pem"
  register: shibboleth_cert

- name: ensure shibboleth privkey exists
  stat:
    path: "{{ SHIBBOLETH_CERTIFICATE_PATH }}/sp-key.pem"
  register: shibboleth_privkey

- name: debug shibboleth cert exists
  debug:
    msg: "There is no shibboleth cert at {{ SHIBBOLETH_CERTIFICATE_PATH }}/sp-cert.pem"
  when: shibboleth_cert.stat.exists == False

- name: debug shibboleth privkey exists
  debug:
    msg: "There is no shibboleth privkey at {{ SHIBBOLETH_CERTIFICATE_PATH }}/sp-key.pem"
  when: shibboleth_privkey.stat.exists == False

- name: fail shibboleth ssl
  fail:
    msg: "Fail shibboleth ssl configs see above"
  when: shibboleth_privkey.stat.exists == False or shibboleth_cert.stat.exists == False


- name: ensure webserver cert exists
  stat:
    path: "{{ HEXAA_FRONTEND_CERTIFICATE_PATH }}/fullchain.pem"
  register: webserver_cert

- name: ensure webserver privkey exists
  stat:
    path: "{{ HEXAA_FRONTEND_CERTIFICATE_PATH }}/privkey.pem"
  register: webserver_privkey

- name: debug webserver cert exists
  debug:
    msg: "There is no webserver cert at {{ HEXAA_FRONTEND_CERTIFICATE_PATH }}/fullchain.pem"
  when: webserver_cert.stat.exists == False

- name: debug webserver privkey exists
  debug:
    msg: "There is no webserver privkey at {{ HEXAA_FRONTEND_CERTIFICATE_PATH }}/privkey.pem"
  when: webserver_privkey.stat.exists == False

- name: fail webserver ssl
  fail:
    msg: "Fail webserver ssl configs see above"
  when: webserver_privkey.stat.exists == False or webserver_cert.stat.exists == False

- name: Set scoped key from backend variable
  set_fact:
    HEXAA_FRONTEND_SCOPED_KEY: "{{ HEXAA_BACKEND_MASTERKEY.defaultMasterKey }}"
  when:
    - HEXAA_FRONTEND_SCOPED_KEY == ""
    - HEXAA_BACKEND_MASTERKEY is defined
    - HEXAA_BACKEND_MASTERKEY.defaultMasterKey is defined

- fail:
    msg: "The HEXAA backend master key is missing"
  when: HEXAA_FRONTEND_SCOPED_KEY == ""

- fail:
    msg: "The HEXAA backend secret is missing"
  when: HEXAA_BACKEND_SECRET == ""


- name: set network list for the main HTTP server container
  set_fact:
    docker_networks: [{name: "{{ docker_network_name_frontend }}"}]
  tags: [web]
- set_fact:
    docker_networks: "{{ [{'name':  docker_network_name_backend}] + docker_networks }}"
  when: docker_network_name_backend is defined
  tags: [web]


- name: create config directory
  file:
    path: /opt/hexaa/config/frontend
    state: directory
  become: true
  register: frontend_config_dir
  tags: web
- name: create ansible generated
  file:
    path: "{{ frontend_config_dir.path }}/00_GENERATED_BY_ANSIBLE"
    state: touch
  become: true
- name: create parameters.yml from template
  template:
    src: parameters.yml.j2
    dest: "{{ frontend_config_dir.path }}/parameters.yml"
  become: true

- name: create log dir
  file:
    path: /opt/hexaa/logs/frontend
    state: directory
    mode: ugo+rwxt
  register: log_dir
  become: true

- name: copy Shibboleth and Apache config
  copy:
    src: files/
    dest: "{{ frontend_config_dir.path }}"
  become: true
  tags: [web]

- name: create shibboleth config dir
  file:
    path: "{{ frontend_config_dir.path }}/shibboleth/"
    owner: www-data
    group: hbit
    state: directory
    mode: 0775
  become: true
  tags: [web]

- name: copy certs from parent role
  copy:
    src: files/certs
    dest: "{{ frontend_config_dir.path }}/shibboleth/"
  become: true
  tags: [web]

- name: create shibboleth2.xml from template
  template:
    src: shibboleth2.xml.j2
    dest: "{{ frontend_config_dir.path }}/shibboleth/shibboleth2.xml"
  become: true
  tags: [web]

- name: use the normal config on port 80
  set_fact:
    apache_default_conf: default-hexaa.conf
  when: HEXAA_FRONTEND_URL_PROTO == "http"
- name: use the redirect config on port 80
  set_fact:
    apache_default_conf: default-hexaa-ssl-redirect.conf
  when: HEXAA_FRONTEND_URL_PROTO == "https"
