---
- name: Ensure network exists
  docker_network:
    name: "{{ docker_network_name_frontend }}"
    state: present



- name: start hexaa-frontend
  tags: [web]
  docker_container:
    name: hexaa-frontend
    image: "hexaaproject/hexaa-newui:{{ docker_image_tag }}"
    restart: yes  # to apply config file changes
    networks:
      - name: "{{ docker_network_name_frontend }}"
    volumes:
      - "{{ frontend_config_dir.path }}/parameters.yml:/opt/hexaa-newui/app/config/parameters.yml:ro"
      - "{{ log_dir.path }}:/opt/hexaa-newui/var/logs"
      # export for the web container
      - /opt/hexaa-newui/web
      - /var/run/php


- name: start hexaa-frontend-web
  docker_container:
    name: hexaa-frontend-web
    image: solazs/apache-shib
    networks: "{{ docker_networks }}"
    ports:
      - 80:80
      - 443:443
    volumes_from:
      # mount the hexaa-newui/web and /var/run/php dirs
      - hexaa-frontend

    volumes:
      - "{{ frontend_config_dir.path }}/shibboleth/shibboleth2.xml:/etc/shibboleth/shibboleth2.xml:ro"
      - "{{ frontend_config_dir.path }}/shibboleth/attribute-map.xml:/etc/shibboleth/attribute-map.xml:ro"
      - "{{ frontend_config_dir.path }}/shibboleth/attribute-policy.xml:/etc/shibboleth/attribute-policy.xml:ro"
      - "{{ frontend_config_dir.path }}/shibboleth/metadata:/etc/shibboleth/metadata:ro"
      - "{{ frontend_config_dir.path }}/shibboleth/certs:/etc/shibboleth/certs:ro"
      - "{{ frontend_config_dir.path }}/default-hexaa.conf:/etc/apache2/sites-enabled/000-default.conf:ro"
      - "{{ frontend_config_dir.path }}/default-hexaa-ssl.conf:/etc/apache2/sites-enabled/000-default-ssl.conf:ro"
      - "{{ HEXAA_FRONTEND_CERTIFICATE_PATH }}:/opt/certs:ro"
      - "{{ SHIBBOLETH_CERTIFICATE_PATH }}:/opt/certs-shib:ro"
    command: "bash -c 'a2enmod proxy proxy_http proxy_ajp proxy_fcgi rewrite deflate headers proxy_balancer proxy_connect proxy_html; httpd-shibd-foreground'"
