---
- name: Ensure network exists
  docker_network:
    name: "{{ docker_network_name_frontend }}"
    state: present

- name: docker registry login
  docker_login:
    registry: "{{ REGISTRY_URL }}"
    username: "{{ REGISTRY_USER }}"
    password: "{{ REGISTRY_PASSWORD }}"
  when: REGISTRY_URL is defined

- name: define volumes list for hexaa-frontend container
  set_fact:
    hexaa_frontend_volumes:
      - "{{ frontend_config_dir.path }}/parameters.yml:/opt/hexaa-frontend/app/config/parameters.yml:ro"
      - "{{ log_dir.path }}:/opt/hexaa-frontend/var/logs"
      # export for the web container
      - /opt/hexaa-frontend/web
      - /var/run/php

- name: define volumes list for hexaa-frontend container
  set_fact:
    hexaa_frontend_volumes: "{{ hexaa_frontend_volumes + hexaa_frontend_additional_volumes }}"

- name: start hexaa-frontend
  docker_container:
    name: hexaa-frontend
    image: "{{ docker_image_name_frontend }}:{{ docker_image_tag_frontend }}"
    restart: yes  # to apply config file changes
    networks:
      - name: "{{ docker_network_name_frontend }}"
    volumes: "{{ hexaa_frontend_volumes }}"
    pull: yes
    restart_policy: "{{ docker_restart_policy }}"

- name: start hexaa-frontend-web
  docker_container:
    name: hexaa-frontend-web
    hostname: hexaa-frontend-web
    image: hexaaproject/apache-shib
    networks: "{{ docker_networks }}"
    ports: "{{ HEXAA_FRONTEND_WEB_PORT }}"
    volumes_from:
      # mount the hexaa-frontend/web and /var/run/php dirs
      - hexaa-frontend
    pull: yes
    restart_policy: "{{ docker_restart_policy }}"

    volumes:
      - "{{ frontend_config_dir.path }}/shibboleth/shibboleth2.xml:/etc/shibboleth/shibboleth2.xml:ro"
      - "{{ frontend_config_dir.path }}/shibboleth/attribute-map.xml:/etc/shibboleth/attribute-map.xml:ro"
      - "{{ frontend_config_dir.path }}/shibboleth/attribute-policy.xml:/etc/shibboleth/attribute-policy.xml:ro"
      - "{{ frontend_config_dir.path }}/shibboleth/metadata:/etc/shibboleth/metadata:ro"
      - "{{ frontend_config_dir.path }}/shibboleth/certs:/etc/shibboleth/certs:ro"
      - "{{ frontend_config_dir.path }}/{{ apache_default_conf }}:/etc/apache2/sites-enabled/000-default.conf:ro"
      - "{{ frontend_config_dir.path }}/default-hexaa-ssl.conf:/etc/apache2/sites-enabled/000-default-ssl.conf:ro"
      - "{{ HEXAA_FRONTEND_CERTIFICATE_PATH }}:/opt/certs:ro"
      - "{{ SHIBBOLETH_CERTIFICATE_PATH }}:/opt/certs-shib"
    env:
      APACHE_SHIB_APACHE_MODULES_TO_START: shib ssl deflate proxy proxy_fcgi proxy_http proxy_html proxy_balancer proxy_ajp proxy_connect rewrite headers
      APACHE_SHIB_SHIB_GENERATE_KEY: "{{ 1 if HEXAA_GENERATE_SELFSIGNED else 0 }}"
      APACHE_SHIB_SHIB_HOSTNAME:     "{{ HEXAA_FRONTEND_URL_HOST }}"
      APACHE_SHIB_SHIB_ENTITY_ID:    "{{ SHIBBOLETH_SP_ENTITYID }}"
      # for Nginx proxy, port is removed:
      VIRTUAL_HOST:  "{{ HEXAA_FRONTEND_URL_HOST | regex_replace(':[0-9]+') }}"
      VIRTUAL_PROTO: "{{ HEXAA_FRONTEND_URL_PROTO }}"
      VIRTUAL_PORT:  "{{ 443 if HEXAA_FRONTEND_URL_PROTO == 'https' else 80 }}"


  tags: [web]
